# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      LIBSDIRPATH: ${{ github.workspace }}\deps
        
    steps:
      - uses: actions/checkout@v4

      - name: Restore Thunderstore deps cache
        id: cache-deps
        uses: actions/cache/restore@v4
        with:
          key: thunderstore-deps-${{ hashFiles('manifest.json') }}
          path: deps

      - name: Download dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $deps = (Get-Content manifest.json | ConvertFrom-Json).dependencies
          New-Item -ItemType Directory -Force -Path deps | Out-Null
          foreach ($dep in $deps) {
            $parts = $dep -split '-'
            $user = $parts[0]; $pkg = $parts[1]; $ver = $parts[2]
            $url = "https://thunderstore.io/package/download/$user/$pkg/$ver"
            $out = "deps\$($user)-$($pkg)-$($ver).zip"
            Write-Host "Fetching $url → $out"
            Invoke-WebRequest -Uri $url -OutFile $out
          }

      - name: Unzip dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Get-ChildItem deps\*.zip | ForEach-Object {
            $zip = $_.FullName
            Write-Host "Extracting $zip"
            Expand-Archive -Path $zip -DestinationPath deps -Force
          }

      - name: Clean files in deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: Get-ChildItem -Path "deps" -File | Where-Object { $_.Name -ne "version.dll" } | Remove-Item -Force

      - name: Save Thunderstore deps cache
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: thunderstore-deps-${{ hashFiles('manifest.json') }}
          path: deps

      - name: Download steamcmd
        shell: pwsh
        run: |
          $steamcmdUrl = "https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip"
          $steamcmdZip = "steamcmd.zip"
          Write-Host "Downloading steamcmd from $steamcmdUrl"
          Invoke-WebRequest -Uri $steamcmdUrl -OutFile $steamcmdZip
          Write-Host "Extracting steamcmd"
          Expand-Archive -Path $steamcmdZip -DestinationPath . -Force

      - name: Install steamcmd
        shell: cmd
        run: steamcmd +quit
        continue-on-error: true

      - name: Get RUMBLE version
        shell: pwsh
        run: |
          $output = .\steamcmd.exe +login anonymous +app_info_print 890550 +quit
          $buildidLine = $output | Where-Object { $_ -match '"buildid"' }
          $buildid = $buildidLine -replace '.*"buildid"\s+"(\d+)".*', '$1'
          echo "RUMBLEVER=$buildid" >> $env:GITHUB_ENV
          echo "RUMBLEVER=$buildid"

      - name: Get MelonLoader version
        shell: pwsh
        run: |
          $melon_ver = ((Get-Content manifest.json | ConvertFrom-Json).dependencies | Where-Object { $_ -match 'MelonLoader' }) -replace '.*-',''
          echo "MELONLOADERVER=$melon_ver" >> $env:GITHUB_ENV
          echo "MELONLOADERVER=$melon_ver"

      - name: Restore il2cpp cache
        id: cache-il2cpp
        if: ${{ env.RUMBLEVER != '' && env.MELONLOADERVER != '' }}
        uses: actions/cache/restore@v4
        with:
          key: il2cpp-${{ env.RUMBLEVER }}-${{ env.MELONLOADERVER }}
          path: deps\MelonLoader\Il2CppAssemblies

      - name: Decode Steam config
        if: steps.cache-il2cpp.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $content = @"
          ${{ secrets.STEAM_CERTIFICATE }}
          "@
          $content | Out-File -Encoding ascii steamconfig.b64
          if (Test-Path "config\config.vdf") { Remove-Item "config\config.vdf" -Force }
          certutil -decode steamconfig.b64 config\config.vdf

      - name: Setup install dir
        if: steps.cache-il2cpp.outputs.cache-hit != 'true'
        shell: cmd
        run: steamcmd +force_install_dir .\deps\ +login ${{ secrets.STEAM_USERNAME }} +app_update 890550 validate +quit

      - name: Run EXE until folder exists
        if: steps.cache-il2cpp.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $folderPath = "deps\MelonLoader\Il2CppAssemblies\"

          Start-Process -FilePath "deps\RUMBLE.exe"

          $timeout = 600
          $elapsed = 0
          while (-not (Test-Path $folderPath) -and $elapsed -lt $timeout) {
            Start-Sleep -Seconds 1
            $elapsed++
          }

          if (-not (Test-Path $folderPath)) {
            Write-Error "Timed out waiting for folder: $folderPath"
            exit 1
          } else {
            Start-Sleep -Seconds 10
          }

      - name: Save il2cpp cache
        if: ${{ env.RUMBLEVER != '' && env.MELONLOADERVER != '' && steps.cache-il2cpp.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          key: il2cpp-${{ env.RUMBLEVER }}-${{ env.MELONLOADERVER }}
          path: deps\MelonLoader\Il2CppAssemblies

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
        
      - name: Build
        run: dotnet build --configuration Release /p:PlatformTarget=x64 /p:LIBSDIRPATH=${{ env.LIBSDIRPATH }}
      
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal /p:PlatformTarget=x64 /p:LIBSDIRPATH=${{ env.LIBSDIRPATH }}
