# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      LIBSDIRPATH: ${{ github.workspace }}/deps
      DepotDownloaderVer: DepotDownloader_3.4.0
      Cpp2ILVer: 2022.1.0-pre-release.19
      ManifestId: "1922173029348684036"
        
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        shell: pwsh
        run: |
          $deps = (Get-Content manifest.json | ConvertFrom-Json).dependencies
          New-Item -ItemType Directory -Force -Path deps | Out-Null
          foreach ($dep in $deps) {
            $parts = $dep -split '-'
            $user = $parts[0]; $pkg = $parts[1]; $ver = $parts[2]
            $url = "https://thunderstore.io/package/download/$user/$pkg/$ver"
            $out = "deps\$($user)-$($pkg)-$($ver).zip"
            Write-Host "Fetching $url → $out"
            Invoke-WebRequest -Uri $url -OutFile $out
          }

      - name: Unzip dependencies
        shell: pwsh
        run: |
          Get-ChildItem deps\*.zip | ForEach-Object {
            $zip = $_.FullName
            Write-Host "Extracting $zip"
            Expand-Archive -Path $zip -DestinationPath deps -Force
          }

      - name: Clean files in deps
        shell: pwsh
        run: Get-ChildItem -Path "deps" -File | Remove-Item -Force

      - name: Download steamcmd
        shell: pwsh
        run: |
          $steamcmdUrl = "https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip"
          $steamcmdZip = "install\steamcmd.zip"
          Write-Host "Downloading steamcmd from $steamcmdUrl"
          Invoke-WebRequest -Uri $steamcmdUrl -OutFile $steamcmdZip
          Write-Host "Extracting steamcmd"
          Expand-Archive -Path $steamcmdZip -DestinationPath install -Force

      - name: Install RUMBLE
        shell: cmd
        run: install\steamcmd.exe ^
          +login ${{ secrets.STEAM_USERNAME }} ^
          +force_install_dir ./deps/ ^
          +app_update 890550 validate ^
          +quit

      - name: test
        shell: cmd
        run: ls -R deps\

      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '6.0.x'
        
      # - name: Build
      #   run: dotnet build --configuration Release /p:LIBSDIRPATH=${{ env.LIBSDIRPATH }} -p:PlatformTarget=x64
      
      # - name: Test
      #   run: dotnet test --configuration Release --no-build --verbosity normal /p:LIBSDIRPATH=${{ env.LIBSDIRPATH }} -p:PlatformTarget=x64
